LOGGING:
  LEVEL: "INFO"
  LOG_DIR: 'log_dir'
  FORMAT:  '%(asctime)s %(filename)s: %(message)s'
  DATEFMT: '%Y-%m-%d %H:%M:%S'

INIT:
  GPS_GENERATOR_PATH: 'gps_synth_test.gps_generator'
  GPS_GENERATOR_CLASS: 'GPS_Generator'

GPS_GENERATION:
  COMMON:
    PLACE_NAME: 'Tartu, Tartu linn, Tartu maakond, Estonia'
    DATE_BEGGINING: '2022-07-22'
    DATE_END: '2022-07-25'

  PROFILES:
    PROFILE_1:
      PROFILE_NAME: 'adult_employed_walking'
      NUM_USERS: 2

      NETWORK_PARAMS:
         NETWORK_MODULE_PATH: 'gps_synth_test.network'
         NETWORK_CLASS: 'Network'
         NETWORK_TYPE: 'walk'
         OSM_TAGS_FOR_HOME_AND_WORK: ['building']
         OSM_TAGS_FOR_EVENT: ["amenity", "leisure", 'tourism']

      USER_PARAMS: 
        USER_MODULE_PATH: 'gps_synth_test.user'
        USER_CLASS: 'User_walk'
        MIN_DISTANCE_H_W: 300
        MIN_DISTANCE_W_R: 200
        MEAN_VELOCITY_MS: 1.1
        PROXIMITY_TO_ROAD: 2

OUTPUT:            
  NETWORK_TABLES: 'output_files\network_tables'
  METADATA: 'output_files\metadata'
  GPS: 'output_files\gps_data' 



